### ISSUE TITLE
Domain update task never runs

### ISSUE THREAD

**Issue by sanictaels** [GhostManager/Shepherd#7]
running update domain categories doesnt work. Page will state task is queued but going to administration page and checking scheduled/failed/successful task all shows nothing.

**Comment by chrismaddalena** [comment]
Do you have Redis running and qcluster? The queued tasks will only run if both of those are running.

**Comment by sanictaels** [comment]
> Do you have Redis running and qcluster? The queued tasks will only run if both of those are running.

My bad.
