### ISSUE TITLE
Domain Updates Failed

### ISSUE THREAD

**Issue by kcoble** [GhostManager/Shepherd#8]
Get the following error when running the Domain Update

` 
argument of type 'NoneType' is not iterable : Traceback (most recent call last):
File "/usr/local/lib/python3.7/dist-packages/django_q/cluster.py", line 377, in worker
res = f(*task['args'], **task['kwargs'])
File "/opt/Shepherd/tasks.py", line 103, in check_domains
lab_results = domain_review.check_domain_status()
File "/opt/Shepherd/modules/review.py", line 421, in check_domain_status
if 'categories' in vt_results:
TypeError: argument of type 'NoneType' is not iterable`

**Comment by mut8nt** [comment]
This appears to take place when the VirusTotal API key is not configured. The error is not helpful at all but running through the code revealed the issue. You can request a free API key [here](https://www.virustotal.com/gui/join-us) and configure it in the `settings.py` file.

**Comment by chrismaddalena** [comment]
What @mut8nt mentioned above is accurate. The code changed a ton in the big August release for BlackHat, but that code has not moved over to the standalone Shepherd repo just yet. I plan to bring over those changes  (from Ghostwriter) next week.
